name: "Run linting of terraform code with TFLint"
description: |
  Given a working directory this will perform linting with TFLint.
author: "Peder Schmedling"
inputs:
  working-directory:
    description: From what directory to run TFLint.
    required: true
  config-file-path:
    description: |
      The path to a TFLint config file to use.
      If not specified, the action will attempt to locate a config file to use.
    required: false
    default: ""
  github-token:
    description: |
      GitHub token to use for downloading tflint plugins from GitHub during init.
      See https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - id: check-prereqs
      shell: bash
      run: |
        # Make sure TFLint is available

        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;

        start-group "check prerequisite: TFLint binary"
        if ! command -v tflint --version &>/dev/null; then
          log-error "TFLint is not available on path, please install using the 'setup-tflint' action!"
          exit 1
        else
          log-info "using $(tflint --version)"
        fi
        end-group
    - id: get-config
      shell: bash
      env:
        input_working_directory: ${{ inputs.working-directory }}
        input_config_file_path: ${{ inputs.config-file-path }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_get_config.sh"
    - id: lint
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        input_working_directory: ${{ inputs.working-directory }}
        input_config_file: ${{ steps.get-config.outputs.file }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_lint.sh"
