name: "Run terraform fmt"
description: |
  Run 'terraform fmt', optionally from repository root.
author: "Peder Schmedling"
inputs:
  working-directory:
    description: From what directory to invoke terraform.
    required: true
  format-check-in-root-dir:
    description: |
      If 'true' the command invocation will be performed in the root directory of the repository.
    required: true
runs:
  using: "composite"
  steps:
    - id: check-prereqs
      shell: bash
      run: |
        # Make sure terraform is available

        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;

        start-group "check prerequisite: terraform binary"
        if ! command -v terraform version &>/dev/null; then
          log-error "terraform is not available on path, please install using the 'setup-terraform' action!"
          exit 1
        else
          log-info "using $(terraform version)"
        fi
        end-group
    - id: fmt
      shell: bash
      env:
        TF_IN_AUTOMATION: "true"
        input_working_directory: ${{ inputs.working-directory }}
        input_format_check_in_root_dir: ${{ inputs.format-check-in-root-dir }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_fmt.sh"
