name: "Install a given version of TFLint and make available to subsequent action steps"
description: |
  Downloads TFLint, installs it into the actions runners tool cache and adds it's path to the systems `PATH` environment variable.
author: "Peder Schmedling"
inputs:
  tflint-version:
    description: |
      What version of tflint to use.
      See https://github.com/terraform-linters/tflint/releases
    required: false
    default: latest
  config-file-path:
    description: |
      The path to a TFLint config file to use.
      If not specified, the action will attempt to locate a config file to use.
    required: false
    default: ""
  github-token:
    description: |
      GitHub token to use for downloading tflint plugins from GitHub during init.
      See https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
    required: false
    default: ${{ github.token }}
  working-directory:
    description: From what directory to run TFLint, this path is used to locate a TFLint config file.
    required: true
outputs:
  installed-version:
    description: Actual version that was installed. can be interesting when using 'latest' as input.
    value: ${{ steps.get-meta.outputs.tag-name }}
  bin-path:
    description: Path to binary file that was installed.
    value: ${{ steps.get-meta.outputs.install-bin-path }}
runs:
  using: "composite"
  steps:
    - id: get-meta
      shell: bash
      env:
        input_tflint_version: ${{ inputs.tflint-version }}
        input_github_token: ${{ inputs.github-token }}
        input_runner_tool_cache: ${{ runner.tool_cache }}
        input_runner_os: ${{ runner.os }}
        input_runner_arch: ${{ runner.arch }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_get_meta.sh"

    - id: get-config
      shell: bash
      env:
        input_config_file_path: ${{ inputs.config-file-path }}
        input_working_directory: ${{ inputs.working-directory }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_get_config.sh"

    # attempt to retrieve tflint binary from GitHub cache
    # note: this will also save the binary to GitHub cache in cases where the binary must be downloaded and installed
    - id: cache-tflint
      uses: actions/cache@v5
      with:
        path: ${{ steps.get-meta.outputs.install-dir }}
        key: ${{ steps.get-meta.outputs.cache-key }}

    # attempt to retrieve tflint plugins from GitHub cache
    # note: this will also save the plugins to GitHub cache in cases where the plugins must be downloaded and installed
    - id: cache-tflint-plugins
      uses: actions/cache@v5
      with:
        path: "~/.tflint.d/plugins"
        key: "tflint-plugins-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(steps.get-config.outputs.config-file) }}"

    - id: exists-check
      shell: bash
      env:
        input_install_dir: ${{ steps.get-meta.outputs.install-dir }}
        input_install_bin_path: ${{ steps.get-meta.outputs.install-bin-path }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_exists_check.sh"

    - id: install
      if: steps.exists-check.outputs.already-installed != 'true'
      shell: bash
      env:
        input_download_url: ${{ steps.get-meta.outputs.download-url }}
        input_install_dir: ${{ steps.get-meta.outputs.install-dir }}
        input_install_bin_path: ${{ steps.get-meta.outputs.install-bin-path }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_install.sh"

    - id: add-to-path
      shell: bash
      env:
        input_install_dir: ${{ steps.get-meta.outputs.install-dir }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_add_to_path.sh"
