name: "Parse terraform plan file"
description: |
  Parses a Terraform plan's console output file to extract resource change counts.
  Outputs the number of resources to be added, changed, destroyed, imported, moved, and removed.
author: "Peder Schmedling"
inputs:
  plan-console-file:
    description: Path of file with plan output captured from console.
    required: true
outputs:
  count-add:
    description: Number of resources to be added.
    value: ${{ steps.parse-plan-output.outputs.add-count }}
  count-change:
    description: Number of resources to be changed.
    value: ${{ steps.parse-plan-output.outputs.change-count }}
  count-destroy:
    description: Number of resources to be destroyed.
    value: ${{ steps.parse-plan-output.outputs.destroy-count }}
  count-import:
    description: Number of resources to be imported.
    value: ${{ steps.parse-plan-output.outputs.import-count }}
  count-move:
    description: Number of resources to be moved.
    value: ${{ steps.parse-plan-output.outputs.move-count }}
  count-remove:
    description: Number of resources to be removed.
    value: ${{ steps.parse-plan-output.outputs.remove-count }}
runs:
  using: "composite"
  steps:
    - id: parse-plan-output
      shell: bash
      env:
        input_plan_console_file: ${{ inputs.plan-console-file }}
      run: |
        set -o allexport
        source "${{ github.action_path }}/step_parse_plan_output.sh"
