#!/bin/env bash
#
# Source for the create-validation-summary step
#
# Renders the per-env head and plan-extract bodies for a single environment's
# matrix run. Emitted as two outputs so the caller workflow can post them as
# two separate PR comments: a stable "head" (PATCHed in place across runs,
# pre-allocated by the seed job) and a run-scoped "plan tag" (GC'd at next
# run's seed and re-POSTed).
#
# See docs/Workflow-pr-comments.md for the model.
#
# Required environment variables:
#   input_environment_name     - Name of the current deployment environment
#   input_plan_console_file    - Path of file with plan output captured from console
#   input_plan_txt_output_file - Path of file with plan output generated by terraform
#   input_status_init          - Outcome of init step
#   input_status_verify_lock   - Outcome of lock verification step
#   input_status_fmt           - Outcome of fmt step
#   input_status_validate      - Outcome of validate step
#   input_status_lint          - Outcome of lint step
#   input_status_plan          - Outcome of plan step
#   input_pr_comment_group     - Name of comment group this env belongs to ("" = ungrouped)
#   input_include_plan_details - Whether to include plan details in the summary
#   input_plan_count_add       - Number of resources to be added
#   input_plan_count_change    - Number of resources to be changed
#   input_plan_count_destroy   - Number of resources to be destroyed
#   input_plan_count_import    - Number of resources to be imported
#   input_plan_count_move      - Number of resources to be moved
#   input_plan_count_remove    - Number of resources to be removed
#   input_plan_count_total     - Sum across categories ('' or '?' = not available; ≥0 numeric otherwise)
#   input_plan_has_output_only_changes - 'true' when plan changes outputs only (no resource changes)
#   input_plan_time            - Wall-clock duration of 'terraform plan' formatted as mm:ss (defaults to 'N/A')
#   input_warning_count        - Total warning count across init+validate+plan (numeric; 0/missing/'?' suppresses the row + collapser)
#   input_warnings_markdown_file - Path to rendered warnings markdown; appended as a sibling <details> after the plan-block when non-empty
#   input_job_check_run_id     - The check run ID for the current job
#
# Standard GitHub environment variables used:
#   GITHUB_SERVER_URL  - GitHub server URL
#   GITHUB_REPOSITORY  - Repository owner/name
#   GITHUB_RUN_ID      - Workflow run ID
#

set +o nounset # allow unset variables (graceful handling of defaults)

# Load helpers
source "${GITHUB_ACTION_PATH}/helpers.sh"

# ============================================================================
# head-summary renderer
# ============================================================================
#
# Body shape:
#   ### Terraform validation summary for environment: `<env>`
#   <validation table — ungrouped mode only>
#   <blank>
#   [Job log](<url>)
#
# In grouped mode (input_pr_comment_group non-empty), the validation table
# is omitted — it lives on the per-group head posted by
# aggregate-validation-summaries.
#
# Kept in sync with the grouped head (aggregate-validation-summaries'
# render_group_body): same row set, labels, col-1 icon tooltips (via
# _render_step_icon_cell), and Plan-details / Plan-time / Warnings cell
# conventions and row-presence rules. Two differences are intentional, not
# drift: (1) step-status cells here use text (`success` / <kbd>failure</kbd>
# via format-status) vs emoji in the grouped head — a column-width
# adaptation; (2) the header shape and footer scope differ. See
# docs/Workflow-pr-comments.md §5.1/§5.3.

function render_head_summary {
  local job_url="${1}"

  local head="### Terraform validation summary for environment: \`${input_environment_name}\`"

  # Logs go to stderr so they don't pollute the captured stdout when this
  # function is called via $(). Same trick the rest of the action uses for
  # diagnostic output.
  if [ -n "${input_pr_comment_group}" ]; then
    log-info "grouped mode active (group='${input_pr_comment_group}') — head omits validation table" 1>&2
  else
    log-info "ungrouped mode — head includes full validation table" 1>&2

    # don't touch the indenting here
    head="${head}
|  | Step | Result |
|:---:|---|---|
| $(_render_step_icon_cell "⚙️" "Initialization") | Initialization | $(format-status "${input_status_init}") |
| $(_render_step_icon_cell "🔒" "Lock file") | Lock file | $(format-status "${input_status_verify_lock}") |
| $(_render_step_icon_cell "🖌" "Format and Style") | Format and Style | $(format-status "${input_status_fmt}") |
| $(_render_step_icon_cell "✔" "Validate") | Validate | $(format-status "${input_status_validate}") |
| $(_render_step_icon_cell "🧹" "TFLint") | TFLint | $(format-status "${input_status_lint}") |
| $(_render_step_icon_cell "📖" "Plan") | Plan | $(format-status "${input_status_plan}") |"

    # Warnings row — between Plan and Plan details. Only when count is a
    # positive integer; 0 / unset / '?' suppress it (matches the
    # 'absent when uninteresting' convention used for the per-env head's
    # plan-details vs plan-time rows, and the grouped head's Warnings row).
    # The bodies live in the plan-tag comment via render_plan_extract; the
    # head only carries the count.
    if [[ "${input_warning_count:-0}" =~ ^[0-9]+$ ]] && [ "${input_warning_count}" -gt 0 ]; then
      head="${head}
| $(_render_step_icon_cell "⚠️" "Warnings") | Warnings | <span title=\"Warnings from init+validate+plan\">⚠️ ${input_warning_count}</span> |"
    fi

    if [ "${input_include_plan_details}" == 'true' ]; then

      # Cell wrapped in <div align="left"> to match the grouped head's
      # Plan-details cell byte-for-byte (the grouped table's columns are
      # center-aligned and need the div to anchor the badge stack left; the
      # per-env Result column is already left-aligned so it's a visual
      # no-op, but kept identical for sync).
      # don't touch the indenting here
      head="${head}
| $(_render_step_icon_cell "📊" "Plan details") | Plan details | <div align=\"left\"><span title=\"Resources to be added\">\`💫 ${input_plan_count_add}\` add</span><br><span title=\"Resources to be changed\">\`🛠️ ${input_plan_count_change}\` change</span><br><span title=\"Resources to be destroyed\">\`💥 ${input_plan_count_destroy}\` destroy</span>"

      if [ "${input_plan_count_move}" != '0' ]; then
        head="${head}<br><span title=\"Resources to be moved\">\`🔀 ${input_plan_count_move}\` move</span>"
      fi
      if [ "${input_plan_count_import}" != '0' ]; then
        head="${head}<br><span title=\"Resources to be imported\">\`📥 ${input_plan_count_import}\` import</span>"
      fi
      if [ "${input_plan_count_remove}" != '0' ]; then
        head="${head}<br><span title=\"Resources to be removed\">\`⛓️‍💥 ${input_plan_count_remove}\` remove</span>"
      fi

      head="${head}</div> |"
    fi

    # Plan time row. Default is the em-dash '—' (not backtick-wrapped),
    # matching the grouped head's _render_plan_time_cell: a real duration is
    # backtick-wrapped, an absent/N-A one renders as '—'. The action.yml
    # input default is the literal 'N/A', so treat both empty and 'N/A' as
    # absent here.
    # don't touch the indenting here
    local plan_time_cell
    if [ -z "${input_plan_time:-}" ] || [ "${input_plan_time}" = 'N/A' ]; then
      plan_time_cell="<span title=\"mm:ss (minutes:seconds)\">—</span>"
    else
      plan_time_cell="<span title=\"mm:ss (minutes:seconds)\">\`${input_plan_time}\`</span>"
    fi
    head="${head}
| $(_render_step_icon_cell "⏱" "Plan time") | Plan time | ${plan_time_cell} |"

    # Links row — only rendered when the caller supplied
    # plan-tag-comment-id (typically the id of this run's per-env plan tag,
    # captured from pr-comment's POST output). Mirrors the per-group head's
    # Links column (docs/Workflow-pr-comments.md §6.3) so reviewers learn
    # one navigation pattern.
    # When the Links row is rendered, the standalone '[Job log]' footer
    # below the table is dropped — the same link sits inside the cell.
    if [ -n "${input_plan_tag_comment_id:-}" ]; then
      # don't touch the indenting here
      head="${head}
| $(_render_step_icon_cell "🔗" "Links") | Links | [log extract](#issuecomment-${input_plan_tag_comment_id})<br>[job log](${job_url}) |"
    fi
  fi

  if [ -z "${input_plan_tag_comment_id:-}" ] || [ -n "${input_pr_comment_group}" ]; then
    # Legacy / grouped path: keep the standalone '[Job log]' footer outside
    # the table. Grouped mode still uses it (table is omitted entirely, so
    # the footer is all that's there); ungrouped without a plan-tag-id
    # supplied keeps the old shape for backwards compatibility.
    head="${head}

[Job log](${job_url})"
  fi

  printf '%s' "${head}"
}

# ============================================================================
# plan-extract renderer
# ============================================================================
#
# Body shape:
#   ### Terraform plan for environment: `<env>`
#   <blank>
#   <plan-block — one of the four shapes documented below>
#
# Plan-block shapes:
#   1. plan-count-total numeric 0 AND not output-only → 'Plan: no changes ✅'
#   2. plan-count-total numeric 0 AND output-only     → '<details>Plan: output-only changes ℹ️…'
#   3. plan-count-total numeric > 0                   → '<details>Plan: N changes ℹ️…'
#   4. plan-count-total missing/'?'                   → '<details>Show Plan (last 65k characters)…'
# When plan output is entirely absent, render 'Plan not available 🤷‍♀️'.

# --- helpers used by render_plan_extract ---

# Byte-budgeted tail that always lands on a line boundary. Two motivations:
#  (a) UTF-8 safety: 'tail -c <N>' can cut mid-codepoint when the file
#      contains multi-byte chars; the resulting partial-codepoint at the
#      start of the slice corrupts the rendered comment.
#  (b) Readability: cutting mid-line leaves a dangling fragment at the
#      top of the plan block; reviewers see ' ... whatever_var = '.
# Strategy: 'tail -c <budget>' is byte-safe wrt the total length; piping
# through 'sed 1d' discards the first (possibly-partial) line, which is
# always whole bytes since a newline is a single ASCII byte. The result
# is guaranteed to be line-aligned, slightly under the byte budget.
# Files smaller than the budget pass through unchanged.
function line_anchored_tail {
  local file="$1"
  local budget="$2"
  [ "${budget}" -le 0 ] && return 0
  [ -z "${file}" ] && return 0
  [ ! -f "${file}" ] && return 0
  local file_size
  file_size=$(wc -c <"${file}")
  if [ "${file_size}" -le "${budget}" ]; then
    cat "${file}"
    return
  fi
  tail -c "${budget}" "${file}" | sed '1d'
}

# Reads the warnings markdown file, capping its size at WARN_CAP. Block
# boundary in our rendered markdown is "\n---\n" between every warning,
# so we cut at a newline boundary (same UTF-8 trick as line_anchored_tail)
# and append a clear "(truncated)" footer so reviewers know to look at
# the job log for the full list. Empty / missing file returns empty.
function load_warnings_md {
  local file="$1"
  local cap="$2"
  [ -z "${file}" ] && return 0
  [ ! -s "${file}" ] && return 0
  local file_size
  file_size=$(wc -c <"${file}")
  if [ "${file_size}" -le "${cap}" ]; then
    cat "${file}"
    return
  fi
  local truncated
  truncated=$(head -c "${cap}" "${file}")
  # Strip the partial trailing line (cut may land mid-line).
  if [[ "${truncated}" == *$'\n'* ]]; then
    truncated="${truncated%$'\n'*}"
    truncated="${truncated}"$'\n'
  fi
  printf '%s\n_(truncated, warnings exceed %d bytes — see job log)_\n' \
    "${truncated}" "${cap}"
}

function render_plan_extract {
  local plan="### Terraform plan for environment: \`${input_environment_name}\`"

  # GitHub's comment-body limit is 65536; we cap at 65000 to leave headroom
  # under that AND under Linux's per-string execve limit (MAX_ARG_STRLEN,
  # 128k on Ubuntu) in case this output ever ends up in envp.
  # Budget model: warnings have priority over plan extract — when both
  # can't fit, plan extract is trimmed first. See docs/Plan-warnings.md §5.
  local HARD_LIMIT=65000
  local OVERHEAD=500   # headers, <details> wrappers, blank-line separators
  local WARN_CAP=60000 # warnings get most-but-not-all of the budget

  local warnings_md=""
  warnings_md=$(load_warnings_md "${input_warnings_markdown_file:-}" "${WARN_CAP}")
  local warnings_size
  warnings_size=$(printf '%s' "${warnings_md}" | wc -c)

  local plan_budget=$((HARD_LIMIT - OVERHEAD - warnings_size))
  [ "${plan_budget}" -lt 0 ] && plan_budget=0

  # Pick the source file for plan output. txt-output-file is the post-
  # 'terraform show' rendering (cleanest); console file is the raw tee.
  # For the console file, slice out everything below the "Terraform used
  # the selected providers…" header so we drop init/refresh noise above.
  local source_file=""
  local sliced_console=""
  if [ -f "${input_plan_txt_output_file:-}" ]; then
    source_file="${input_plan_txt_output_file}"
  elif [ -f "${input_plan_console_file:-}" ]; then
    sliced_console="${RUNNER_TEMP:-/tmp}/plan-sliced-$$.txt"
    sed -n '/Terraform used the selected providers to generate the following execution/,$p' \
      "${input_plan_console_file}" >"${sliced_console}"
    source_file="${sliced_console}"
  fi

  local plan_out=""
  if [ -n "${source_file}" ] && [ -s "${source_file}" ]; then
    plan_out=$(line_anchored_tail "${source_file}" "${plan_budget}")
  fi

  local total="${input_plan_count_total:-}"
  local output_only="${input_plan_has_output_only_changes:-false}"

  if [ -z "${plan_out}" ]; then
    plan="${plan}

Plan not available 🤷‍♀️"
  elif [[ "${total}" =~ ^[0-9]+$ ]] && [ "${total}" -eq 0 ] && [ "${output_only}" != 'true' ]; then
    plan="${plan}

Plan: no changes ✅"
  elif [[ "${total}" =~ ^[0-9]+$ ]] && [ "${total}" -eq 0 ] && [ "${output_only}" = 'true' ]; then
    # don't touch the indenting here
    plan="${plan}

<details><summary>Plan: output-only changes ℹ️</summary>

\`\`\`terraform
${plan_out}
\`\`\`
</details>"
  elif [[ "${total}" =~ ^[0-9]+$ ]]; then
    # don't touch the indenting here
    plan="${plan}

<details><summary>Plan: ${total} changes ℹ️</summary>

\`\`\`terraform
${plan_out}
\`\`\`
</details>"
  else
    # don't touch the indenting here
    plan="${plan}

<details><summary>Show Plan (last 65k characters)</summary>

\`\`\`terraform
${plan_out}
\`\`\`
</details>"
  fi

  # Warnings collapser — sibling of the plan-block, appended after it.
  # Rendered regardless of plan-block shape, including 'no changes ✅' —
  # warnings are interesting even when the plan itself is.
  if [ -n "${warnings_md}" ]; then
    local warning_count="${input_warning_count:-0}"
    [[ "${warning_count}" =~ ^[0-9]+$ ]] || warning_count=0
    # don't touch the indenting here
    plan="${plan}

<details><summary>⚠️ ${warning_count} warnings</summary>

${warnings_md}
</details>"
  fi

  # Clean up the per-call temp slice if we made one.
  [ -n "${sliced_console}" ] && [ -f "${sliced_console}" ] && rm -f "${sliced_console}"

  printf '%s' "${plan}"
}

# ============================================================================
# Main
# ============================================================================

function main {
  log-info "rendering per-env head + plan-extract bodies ..."

  local job_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/job/${input_job_check_run_id}#logs"

  local head_summary plan_extract
  head_summary=$(render_head_summary "${job_url}")
  plan_extract=$(render_plan_extract)

  log-multiline "head-summary " "${head_summary}"
  log-multiline "plan-extract " "${plan_extract}"

  # Back-compat outputs: the legacy `summary` + `prefix` outputs are kept so
  # callers still on the pre-overhaul commenting flow (e.g. terraform-module-ci
  # via comment-on-pr@v2's delete-by-prefix mechanism) continue to work.
  # Both outputs are deprecated and will be dropped once those callers migrate
  # to head-summary/plan-extract + the pr-comment action.
  local legacy_prefix="### Terraform validation summary for environment: \`${input_environment_name}\`"
  local legacy_summary
  legacy_summary=$(printf '%s\n%s' "${head_summary}" "${plan_extract}")

  set-multiline-output 'head-summary' "${head_summary}"
  set-multiline-output 'plan-extract' "${plan_extract}"
  set-output 'prefix' "${legacy_prefix}"
  set-multiline-output 'summary' "${legacy_summary}"

  log-info "create-validation-summary completed."
  return 0
}

main
_main_exit_code=$?
exit ${_main_exit_code}
