#!/bin/env bash
#
# Source for the create-validation-summary step
#
# Creates a pull request comment with a summary of terraform validation results
# and the last 65k characters of terraform plan output.
#
# Required environment variables:
#   input_environment_name     - Name of the current deployment environment
#   input_plan_console_file    - Path of file with plan output captured from console
#   input_plan_txt_output_file - Path of file with plan output generated by terraform
#   input_status_init          - Outcome of init step
#   input_status_fmt           - Outcome of fmt step
#   input_status_validate      - Outcome of validate step
#   input_status_lint          - Outcome of lint step
#   input_status_plan          - Outcome of plan step
#   input_include_plan_details - Whether to include plan details in the summary
#   input_plan_count_add       - Number of resources to be added
#   input_plan_count_change    - Number of resources to be changed
#   input_plan_count_destroy   - Number of resources to be destroyed
#   input_plan_count_import    - Number of resources to be imported
#   input_plan_count_move      - Number of resources to be moved
#   input_plan_count_remove    - Number of resources to be removed
#   input_job_check_run_id     - The check run ID for the current job
#   input_github_actor         - The GitHub actor who triggered the workflow
#   input_github_event_name    - The GitHub event name that triggered the workflow
#
# Standard GitHub environment variables used:
#   GITHUB_SERVER_URL  - GitHub server URL
#   GITHUB_REPOSITORY  - Repository owner/name
#   GITHUB_RUN_ID      - Workflow run ID
#   GITHUB_WORKFLOW    - Workflow name
#

set +o nounset # allow unset variables (graceful handling of defaults)

# Load helpers
source "${GITHUB_ACTION_PATH}/helpers.sh"

# ============================================================================
# Main Logic
# ============================================================================

function main {
  log-info "creating pull request comment ..."

  local comment_prefix="### Terraform validation summary for environment: \`${input_environment_name}\`"

  # Build the validation summary table
  # don't touch the indenting here
  local comment_content="${comment_prefix}
|  | Step | Result |
|:---:|---|---|
| ⚙️ | Initialization | $(format-status "${input_status_init}") |
| 🖌 | Format and Style | $(format-status "${input_status_fmt}") |
| ✔ | Validate | $(format-status "${input_status_validate}") |
| 🧹 | TFLint | $(format-status "${input_status_lint}") |
| 📖 | Plan | $(format-status "${input_status_plan}") |"

  # Add plan details if enabled
  if [ "${input_include_plan_details}" == 'true' ]; then

    # don't touch the indenting here
    comment_content="${comment_content}
| 📊 | Plan Details | <span title=\"Resources to be added\">\`💫 ${input_plan_count_add}\` add</span><br><span title=\"Resources to be changed\">\`🛠️ ${input_plan_count_change}\` change</span><br><span title=\"Resources to be destroyed\">\`💥 ${input_plan_count_destroy}\` destroy</span>"

    if [ "${input_plan_count_move}" != '0' ]; then
      comment_content="${comment_content}<br><span title=\"Resources to be moved\">\`🔀 ${input_plan_count_move}\` move</span>"
    fi

    if [ "${input_plan_count_import}" != '0' ]; then
      comment_content="${comment_content}<br><span title=\"Resources to be imported\">\`📥 ${input_plan_count_import}\` import</span>"
    fi

    if [ "${input_plan_count_remove}" != '0' ]; then
      comment_content="${comment_content}<br><span title=\"Resources to be removed\">\`⛓️‍💥 ${input_plan_count_remove}\` remove</span>"
    fi

    # end of table row
    comment_content="${comment_content} |"
  fi

  # Add link to job logs
  local job_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/job/${input_job_check_run_id}#logs"

  # Look for plan output
  # Read directly from file using tail/sed to avoid loading the entire file into
  # a shell variable. With 'set -o allexport' active, large variables are exported
  # to the environment, which can exceed ARG_MAX and cause 'Argument list too long'
  # errors when forking external commands.
  local plan_out=""
  if [ -f "${input_plan_txt_output_file}" ]; then
    # Prefer the plan output generated by terraform itself
    # Cap at 65k characters to fit within GitHub comment limits
    plan_out=$(tail -c 65000 "${input_plan_txt_output_file}")
  elif [ -f "${input_plan_console_file}" ]; then
    # Fall back to the captured console output
    # Strip state refresh lines and cap at 65k characters in a single pipeline
    plan_out=$(sed -n '/Terraform used the selected providers to generate the following execution/,$p' "${input_plan_console_file}" | tail -c 65000)
  fi

  # Add plan output to comment if available
  if [ -n "${plan_out}" ]; then

    # don't touch the indenting here
    comment_content="${comment_content}

<details><summary>Show Plan (last 65k characters)</summary>

\`\`\`terraform
${plan_out}
\`\`\`
</details>"
  else
    # don't touch the indenting here
    comment_content="${comment_content}

Plan not available 🤷‍♀️"
  fi

  comment_content="${comment_content}

*Pusher: @${input_github_actor}, Action: \`${input_github_event_name}\`, Workflow: \`${GITHUB_WORKFLOW}\`, Job log: [link](${job_url})*"

  log-info "Final validation summary prefix: ${comment_prefix}"
  log-multiline "Final validation summary " "${comment_content}"

  set-output 'prefix' "${comment_prefix}"
  set-multiline-output 'summary' "${comment_content}"

  log-info "create-validation-summary completed."
  return 0
}

# Run main function
main
_main_exit_code=$?
exit ${_main_exit_code}
