name: "Run terraform test"
description: |
  Terraform test for modules.
author: "Artjoms Laivins"

inputs:
  test-file:
    description: Test file to run.
    required: true

outputs:
  exit-code:
    description: The exit code from the terraform test command.
    value: ${{ steps.run-tests.outputs.exit-code }}
  summary:
    description: Summary of the test run.
    value: ${{ steps.run-tests.outputs.summary }}
  report:
    description: Report file of the test run.
    value: ${{ steps.run-tests.outputs.report }}
  json:
    description: JSON output of the test run.
    value: ${{ steps.run-tests.outputs.json }}


runs:
  using: "composite"
  steps:
    - id: check-prereqs
      shell: bash
      run: |
        # Make sure terraform is available

        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;

        start-group "check prerequisite: terraform binary"
        if ! command -v terraform version &>/dev/null; then
          log-error "terraform is not available on path, please install using the 'setup-terraform' action!"
          exit 1
        else
          log-info "using $(terraform version)"
        fi
        end-group

    - id: azure-login
      uses: azure/login@v3
      with:
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
        client-id: ${{ env.ARM_CLIENT_ID }}

    - id: run-tests
      working-directory: ${{ github.workspace }}
      shell: bash
      continue-on-error: true
      env:
        TF_IN_AUTOMATION: true
        input_test_file: ${{ inputs.test-file }}
      run: |
        # Run 'terraform test' for one test file and build a test report
        set -o allexport
        source "${{ github.action_path }}/step_run_tests.sh"

    - id: upload-test-results
      uses: actions/upload-artifact@v7
      with:
        name: test-results-output-${{ inputs.test-file }}
        path: ${{ steps.run-tests.outputs.json }}

    - id: test-status
      if: ( steps.run-tests.outcome == 'failure' || steps.run-tests.outcome == 'cancelled' )
      shell: bash
      run: |
        # Fail the action because 'terraform test' failed
        exit 1
