#!/bin/env bash
#
# Test runner for terraform-test.
#
# Golden suite for the legacy behaviour. test-data/legacy/<scenario>/ holds
# what the action produced for each scenario BEFORE it was converted from the
# legacy inline-bash layout: the step outputs (normalised), the text report,
# the terraform command line and the step's exit code. The goldens were
# generated by running the legacy `run-tests` step (its real YAML-processed
# run block, extracted with the GitHub expressions substituted) against a fake
# terraform binary (test-data/fake_terraform.sh) that replays JSON logs
# captured from a real Terraform 1.16.2 (test-data/terraform-1.16.2/).
#
# The converted step script must reproduce every golden. Regenerate with
# UPDATE_GOLDENS=1 only when the legacy behaviour is meant to change, and
# review the diff.
#

_this_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0
TESTS_RUN=0

DATA_DIR="${_this_script_dir}/test-data"
FIXTURES="${DATA_DIR}/terraform-1.16.2"
LEGACY_DIR="${DATA_DIR}/legacy"
UPDATE_GOLDENS="${UPDATE_GOLDENS:-}"

# --------------------------------------------------------------------------
# Harness
# --------------------------------------------------------------------------

setup() {
  TEST_TMP="$(mktemp -d)"
  export RUNNER_TEMP="${TEST_TMP}/runner-temp"
  export GITHUB_WORKSPACE="${TEST_TMP}/workspace"
  mkdir -p "${RUNNER_TEMP}" "${GITHUB_WORKSPACE}" "${TEST_TMP}/bin"
  export GITHUB_OUTPUT="${TEST_TMP}/github-output"
  export GITHUB_STEP_SUMMARY="${TEST_TMP}/step-summary"
  : >"${GITHUB_OUTPUT}"
  : >"${GITHUB_STEP_SUMMARY}"
  export GITHUB_ACTION_PATH="${_this_script_dir}"
  export GITHUB_RUN_ID="424242"
  export RUNNER_OS="Linux"
  export RUNNER_ARCH="X64"

  cp "${DATA_DIR}/fake_terraform.sh" "${TEST_TMP}/bin/terraform"
  chmod +x "${TEST_TMP}/bin/terraform"
  export FAKE_TF_LOG="${TEST_TMP}/terraform-calls.log"
  : >"${FAKE_TF_LOG}"
  unset FAKE_TF_OUTPUT FAKE_TF_EXIT FAKE_TF_JUNIT FAKE_TF_STDERR FAKE_TF_VERSION_JSON

  STEP_LOG="${TEST_TMP}/step-output.txt"
  TEST_PATH="${TEST_TMP}/bin:${PATH}"

  # Inputs, as the action.yml shim hands them over.
  export input_test_file="unit-pass.tftest.hcl"
}

teardown() {
  rm -rf "${TEST_TMP}"
}

# Run the test step of the action as GitHub would: from the workspace
# (the step's working-directory), TF_IN_AUTOMATION set by the step's env,
# under the runner's shell flags: the step script sourced under allexport, in
# a subshell so its 'exit' ends only the subshell.
run_step() {
  (
    cd "${GITHUB_WORKSPACE}" || exit 99
    export PATH="${TEST_PATH}"
    export TF_IN_AUTOMATION=true
    set -eo pipefail
    set -o allexport
    source "${_this_script_dir}/step_run_tests.sh"
  ) >"${STEP_LOG}" 2>&1
  LAST_EXIT=$?
}

# The prerequisite check (terraform on PATH): the inline `check-prereqs` run
# block of action.yml, with the action path substituted.
run_prereq_check() {
  local path_value="${1}"
  local step="${TEST_TMP}/prereqs.sh"
  python3 -c '
import sys
import yaml

action_file, out_file, action_path = sys.argv[1:4]
steps = yaml.safe_load(open(action_file, encoding="utf-8"))["runs"]["steps"]
source = next(step["run"] for step in steps if step.get("id") == "check-prereqs")
open(out_file, "w", encoding="utf-8").write(source.replace("${{ github.action_path }}", action_path))
' "${_this_script_dir}/action.yml" "${step}" "${_this_script_dir}" || return 1
  (
    cd "${GITHUB_WORKSPACE}" || exit 99
    export PATH="${path_value}"
    "${BASH}" --noprofile --norc -eo pipefail "${step}"
  ) >"${STEP_LOG}" 2>&1
  LAST_EXIT=$?
}

# A PATH without any terraform: symlinks to the few tools the helpers need.
path_without_terraform() {
  local dir="${TEST_TMP}/bin-no-tf"
  mkdir -p "${dir}"
  local tool
  for tool in basename dirname md5sum head realpath cat jq date sed tee; do
    ln -sf "$(command -v "${tool}")" "${dir}/${tool}"
  done
  echo "${dir}"
}

# Parse GITHUB_OUTPUT (name=value and name<<"delim" forms) into sorted
# name=value lines; multi-line values escaped. Temp and workspace paths and the
# timestamp in the legacy file names are normalised.
normalised_outputs() {
  python3 - "${GITHUB_OUTPUT}" "${GITHUB_WORKSPACE}" "${RUNNER_TEMP}" <<'PY'
import re
import sys

src, workspace, runner_temp = sys.argv[1:4]
lines = open(src, encoding="utf-8").read().split("\n")
outputs = {}
i = 0
while i < len(lines):
    line = lines[i]
    heredoc = re.match(r'^([^=<]+)<<(.+)$', line)
    if heredoc:
        name, delim = heredoc.groups()
        value = []
        i += 1
        while i < len(lines) and lines[i] != delim:
            value.append(lines[i])
            i += 1
        outputs[name] = "\n".join(value)
    elif "=" in line:
        name, _, value = line.partition("=")
        outputs[name] = value
    i += 1


def norm(value):
    value = value.replace(workspace, "<WORKSPACE>").replace(runner_temp, "<RUNNER_TEMP>")
    return re.sub(r"-\d{14}-", "-<TIMESTAMP>-", value)


for name in sorted(outputs):
    print(f"{name}={norm(outputs[name])!r}")
PY
}

output_value() {
  python3 - "${GITHUB_OUTPUT}" "${1}" <<'PY'
import re
import sys

src, wanted = sys.argv[1:3]
lines = open(src, encoding="utf-8").read().split("\n")
i = 0
found = None
while i < len(lines):
    line = lines[i]
    heredoc = re.match(r'^([^=<]+)<<(.+)$', line)
    if heredoc:
        name, delim = heredoc.groups()
        value = []
        i += 1
        while i < len(lines) and lines[i] != delim:
            value.append(lines[i])
            i += 1
        if name == wanted:
            found = "\n".join(value)
    elif "=" in line:
        name, _, value = line.partition("=")
        if name == wanted:
            found = value
    i += 1
sys.stdout.write(found if found is not None else "")
PY
}

normalised_calls() {
  sed -e "s|${GITHUB_WORKSPACE}|<WORKSPACE>|g" -e "s|${RUNNER_TEMP}|<RUNNER_TEMP>|g" "${FAKE_TF_LOG}"
}

assert() {
  local name="${1}"
  shift
  TESTS_RUN=$((TESTS_RUN + 1))
  echo -e "${BLUE}TEST ${TESTS_RUN}: ${name}${NC}"
  if "$@"; then
    echo -e "${GREEN}✓ PASSED${NC}"
    TESTS_PASSED=$((TESTS_PASSED + 1))
  else
    echo -e "${RED}✗ FAILED${NC}"
    echo "--- step output ---"
    cat "${STEP_LOG}" 2>/dev/null || true
    echo "--- GITHUB_OUTPUT ---"
    cat "${GITHUB_OUTPUT}" 2>/dev/null || true
    echo "--- end ---"
    TESTS_FAILED=$((TESTS_FAILED + 1))
  fi
}

# Compare generated text with a golden file; UPDATE_GOLDENS=1 rewrites it.
matches_golden_text() {
  local golden="${1}"
  local actual_file="${2}"
  if [ -n "${UPDATE_GOLDENS}" ]; then
    mkdir -p "$(dirname "${golden}")"
    cp "${actual_file}" "${golden}"
    return 0
  fi
  if cmp -s "${golden}" "${actual_file}"; then
    return 0
  fi
  echo "  differs from ${golden#"${DATA_DIR}/"}:"
  diff "${golden}" "${actual_file}" | sed 's/^/    /'
  return 1
}

legacy_outputs_match() {
  local scenario="${1}"
  normalised_outputs >"${TEST_TMP}/actual-outputs.txt"
  matches_golden_text "${LEGACY_DIR}/${scenario}/outputs.txt" "${TEST_TMP}/actual-outputs.txt"
}

legacy_report_matches() {
  local scenario="${1}"
  local report
  report="$(output_value report)"
  [ -f "${report}" ] || { echo "  report file '${report}' missing"; return 1; }
  matches_golden_text "${LEGACY_DIR}/${scenario}/report.txt" "${report}"
}

legacy_calls_match() {
  local scenario="${1}"
  normalised_calls >"${TEST_TMP}/actual-calls.txt"
  # The legacy step only runs 'terraform test'; version probes are allowed
  # to come and go, so the golden holds the test invocation alone.
  grep -- ' args=test ' "${TEST_TMP}/actual-calls.txt" >"${TEST_TMP}/actual-test-calls.txt"
  matches_golden_text "${LEGACY_DIR}/${scenario}/command.txt" "${TEST_TMP}/actual-test-calls.txt"
}

legacy_exit_matches() {
  local scenario="${1}"
  echo "${LAST_EXIT}" >"${TEST_TMP}/actual-exit.txt"
  matches_golden_text "${LEGACY_DIR}/${scenario}/exit-code.txt" "${TEST_TMP}/actual-exit.txt"
}

# The JSON output file holds terraform's stdout byte for byte.
json_output_is_terraform_stdout() {
  local json
  json="$(output_value json)"
  [ -f "${json}" ] || { echo "  json file '${json}' missing"; return 1; }
  cmp -s "${json}" "${FAKE_TF_OUTPUT}" || { echo "  json file differs from terraform's stdout"; return 1; }
}

log_contains() {
  grep -qF -- "${1}" "${STEP_LOG}" || { echo "  log lacks '${1}'"; return 1; }
}

# Structural assertions on action.yml, one python expression per check.
action_yml_check() {
  python3 - "${_this_script_dir}/action.yml" "${1}" <<'PY'
import sys
import yaml

action = yaml.safe_load(open(sys.argv[1], encoding="utf-8"))
check = sys.argv[2]
inputs = action.get("inputs", {})
outputs = action.get("outputs", {})
steps = action["runs"]["steps"]


def step_index(predicate):
    for index, step in enumerate(steps):
        if predicate(step):
            return index
    return -1


def uses(prefix):
    return lambda step: str(step.get("uses", "")).startswith(prefix)


test_step = step_index(lambda step: step.get("id") == "run-tests")
login = step_index(uses("azure/login@"))
upload = step_index(uses("actions/upload-artifact@"))

checks = {
    "test-file-required": inputs.get("test-file", {}).get("required") is True,
    "legacy-outputs": all(
        "steps.run-tests.outputs." + name in str(outputs.get(name, {}).get("value", ""))
        for name in ("exit-code", "summary", "report", "json")
    ),
    "test-step-shape": test_step >= 0
    and steps[test_step].get("continue-on-error") is True
    and str(steps[test_step].get("working-directory")) == "${{ github.workspace }}"
    and str(steps[test_step].get("env", {}).get("TF_IN_AUTOMATION")).lower() == "true",
    "azure-login-before-test": login >= 0
    and login < test_step
    and steps[login]["uses"] == "azure/login@v3"
    and steps[login].get("with", {}).get("tenant-id") == "${{ env.ARM_TENANT_ID }}"
    and steps[login].get("with", {}).get("subscription-id") == "${{ env.ARM_SUBSCRIPTION_ID }}"
    and steps[login].get("with", {}).get("client-id") == "${{ env.ARM_CLIENT_ID }}",
    "upload-after-test": upload > test_step
    and steps[upload]["uses"] == "actions/upload-artifact@v7"
    and steps[upload].get("with", {}).get("name") == "test-results-output-${{ inputs.test-file }}"
    and steps[upload].get("with", {}).get("path") == "${{ steps.run-tests.outputs.json }}",
    "fails-on-test-failure": "steps.run-tests.outcome == 'failure'" in str(steps[-1].get("if", ""))
    and "exit 1" in str(steps[-1].get("run", "")),
}
ok = checks[check]
if not ok:
    print(f"  structural check '{check}' failed")
sys.exit(0 if ok else 1)
PY
}

echo ""
echo -e "${YELLOW}============================================${NC}"
echo -e "${YELLOW}          TERRAFORM-TEST TEST SUITE         ${NC}"
echo -e "${YELLOW}============================================${NC}"

# --------------------------------------------------------------------------
# L1 — legacy behaviour, pinned per scenario
# --------------------------------------------------------------------------
# scenario | fixture | terraform exit code | test-file input
legacy_scenarios=(
  "pass|pass.json|0|unit-pass.tftest.hcl"
  "assertion-fail|fail.json|1|unit-fail.tftest.hcl"
  "run-error|runerror.json|1|unit-runerror.tftest.hcl"
  "filter-miss|filtermiss.json|0|nosuch.tftest.hcl"
  "parse-error|invalid.json|1|unit-pass.tftest.hcl"
  "not-json|../legacy-input/not-json.txt|1|unit-pass.tftest.hcl"
)

for entry in "${legacy_scenarios[@]}"; do
  IFS='|' read -r scenario fixture tf_exit test_file <<<"${entry}"
  setup
  export FAKE_TF_OUTPUT="${FIXTURES}/${fixture}"
  export FAKE_TF_EXIT="${tf_exit}"
  export input_test_file="${test_file}"
  run_step
  assert "L1 ${scenario}: step exit code" legacy_exit_matches "${scenario}"
  assert "L1 ${scenario}: terraform command line and working directory" legacy_calls_match "${scenario}"
  assert "L1 ${scenario}: outputs" legacy_outputs_match "${scenario}"
  assert "L1 ${scenario}: text report" legacy_report_matches "${scenario}"
  assert "L1 ${scenario}: json output is terraform's stdout" json_output_is_terraform_stdout
  teardown
done

# --------------------------------------------------------------------------
# L2 — prerequisite: terraform on PATH
# --------------------------------------------------------------------------
setup
run_prereq_check "${TEST_PATH}"
assert "L2: terraform on PATH → exit 0" test "${LAST_EXIT}" -eq 0
teardown

setup
run_prereq_check "$(path_without_terraform)"
assert "L2: terraform missing → exit 1" test "${LAST_EXIT}" -eq 1
assert "L2: terraform missing → names the setup action" log_contains "terraform is not available on path"
teardown

# --------------------------------------------------------------------------
# L3 — action.yml: embedded login, upload and the failing gate
# --------------------------------------------------------------------------
setup
assert "L3: test-file is required" action_yml_check test-file-required
assert "L3: legacy outputs exit-code, summary, report, json come from the test step" action_yml_check legacy-outputs
assert "L3: test step runs from the workspace, continue-on-error, TF_IN_AUTOMATION" action_yml_check test-step-shape
assert "L3: azure/login@v3 from ARM_* env runs before the test" action_yml_check azure-login-before-test
assert "L3: the JSON log is uploaded as test-results-output-<test-file>" action_yml_check upload-after-test
assert "L3: the action fails when the test step failed" action_yml_check fails-on-test-failure
teardown

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------
echo ""
echo "========================================"
echo "Tests run:    ${TESTS_RUN}"
echo -e "Tests passed: ${GREEN}${TESTS_PASSED}${NC}"
echo -e "Tests failed: ${RED}${TESTS_FAILED}${NC}"
echo "========================================"

if [[ ${TESTS_FAILED} -gt 0 ]]; then
  exit 1
fi
exit 0
