#!/bin/env bash
#
# Test runner for create-test-report.
#
# Golden-file suite. test-data/golden_<scenario>.md holds the byte-exact body
# the LEGACY inline-bash action produced for each scenario, generated by
# running its `create-test-summary` step through extract_step_source.py —
# the real YAML-processed run block, not a transcription of it. The
# converted step script must reproduce every golden byte for byte
# (docs/Apply-and-destroy-reporting.md P23, J1).
#
# One intentional divergence from legacy, asserted rather than pinned: a
# report over the 65k budget is cut on a line boundary and never
# mid-codepoint (J2). The legacy `tail -c 65000` did neither.
#

_this_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0
TESTS_RUN=0

DATA_DIR="${_this_script_dir}/test-data"
OUT_FILE=/tmp/test_output_create_test_report.txt

# --------------------------------------------------------------------------
# Harness
# --------------------------------------------------------------------------

setup() {
  export GITHUB_OUTPUT=$(mktemp)
  export RUNNER_TEMP=$(mktemp -d)
  export GITHUB_ACTION_PATH="${_this_script_dir}"
  export GITHUB_WORKSPACE="${RUNNER_TEMP}"
  export GITHUB_WORKFLOW="DSB Terraform Module CI"
  export GITHUB_ACTOR="octo-user"
  export GITHUB_EVENT_NAME="pull_request"

  # Inputs, as the action.yml shim exports them.
  export input_test_file="main.tftest.hcl"
  export input_test_out_file="${RUNNER_TEMP}/results.json"
  export input_status_init="success"
  export input_status_test="success"
  export input_test_summary='"Success! 2 passed, 0 failed."'
  export input_test_report="${DATA_DIR}/report_success.txt"

  # The step redacts these variables' values; a developer's own session must
  # not leak into the goldens.
  unset ARM_SUBSCRIPTION_ID ARM_TENANT_ID ARM_CLIENT_ID ARM_CLIENT_SECRET \
    ARM_CLIENT_CERTIFICATE_PASSWORD ARM_OIDC_TOKEN ARM_OIDC_REQUEST_TOKEN \
    ARM_ACCESS_KEY ARM_SAS_TOKEN
}

teardown() {
  rm -f "${GITHUB_OUTPUT}"
  rm -rf "${RUNNER_TEMP}"
}

# Run the step script in a subshell, under the runner's shell flags. No
# allexport — the action.yml shim deliberately omits it (65k body in a
# local; see the shim comment), and the harness must match production.
run_step() {
  (
    set -eo pipefail
    source "${_this_script_dir}/step_create_test_report.sh"
  ) >"${OUT_FILE}" 2>&1
  LAST_EXIT=$?
}

# The rendered body: the file named by the `body-file` output.
rendered_body_file() {
  grep '^body-file=' "${GITHUB_OUTPUT}" | head -n1 | cut -d= -f2-
}

assert() {
  local name="${1}"
  shift
  TESTS_RUN=$((TESTS_RUN + 1))
  echo -e "${BLUE}TEST ${TESTS_RUN}: ${name}${NC}"
  if "$@"; then
    echo -e "${GREEN}✓ PASSED${NC}"
    TESTS_PASSED=$((TESTS_PASSED + 1))
  else
    echo -e "${RED}✗ FAILED${NC}"
    echo "--- step output ---"
    cat "${OUT_FILE}" 2>/dev/null || true
    echo "--- GITHUB_OUTPUT ---"
    cat "${GITHUB_OUTPUT}" 2>/dev/null || true
    echo "--- end ---"
    TESTS_FAILED=$((TESTS_FAILED + 1))
  fi
}

# Byte-exact comparison against a golden, with a diff on failure.
matches_golden() {
  local golden="${DATA_DIR}/golden_${1}.md"
  local actual
  actual="$(rendered_body_file)"
  if cmp -s "${golden}" "${actual}"; then
    return 0
  fi
  echo "  body differs from ${golden##*/}:"
  diff "${golden}" "${actual}" | sed 's/^/    /'
  return 1
}

echo ""
echo -e "${YELLOW}============================================${NC}"
echo -e "${YELLOW}        CREATE-TEST-REPORT GOLDEN TESTS      ${NC}"
echo -e "${YELLOW}============================================${NC}"

# --------------------------------------------------------------------------
# J1 — every pinned scenario reproduces its golden byte for byte
# --------------------------------------------------------------------------

setup
run_step
assert "J1: success with report → golden" test "${LAST_EXIT}" -eq 0
assert "J1: success with report → byte-exact" matches_golden success_with_report
teardown

setup
export input_status_test="failure"
export input_test_summary='"Failure! 1 passed, 1 failed."'
export input_test_report="${DATA_DIR}/report_failure.txt"
run_step
assert "J1: failure with report → byte-exact" matches_golden failure_with_report
teardown

setup
export input_test_report="${RUNNER_TEMP}/does-not-exist.txt"
run_step
assert "J3: report file missing → exit 0" test "${LAST_EXIT}" -eq 0
assert "J3: report file missing → 'Test report not available' golden" matches_golden report_missing
teardown

setup
export input_status_init="failure"
export input_status_test="skipped"
export input_test_summary=""
export input_test_report="${RUNNER_TEMP}/does-not-exist.txt"
run_step
assert "J1: init failed, tests skipped → <kbd> cells golden" matches_golden init_failed
teardown

setup
export input_status_test="failure"
export input_test_summary='"Error: test run aborted"'
export input_test_report="${DATA_DIR}/report_failure.txt"
run_step
assert "J5: summary without 'Success!' → ❌ golden" matches_golden summary_not_success
teardown

setup
export input_test_file="øæå.tftest.hcl"
export input_test_report="${DATA_DIR}/report_nonascii.txt"
run_step
assert "J7: non-ASCII file name and report → byte-exact" matches_golden non_ascii
teardown


# --------------------------------------------------------------------------
# J4 — body-file output: path exists, is readable, holds the whole body
# --------------------------------------------------------------------------
setup
run_step
_bf="$(rendered_body_file)"
assert "J4: body-file output is set" test -n "${_bf}"
assert "J4: body-file exists and is non-empty" test -s "${_bf}"
assert "J4: body-file lives under RUNNER_TEMP" bash -c "[[ '${_bf}' == '${RUNNER_TEMP}'/* ]]"
assert "J4: body-file content is the golden body" cmp -s "${DATA_DIR}/golden_success_with_report.md" "${_bf}"
# The body must not also be a step output — that is what puts it into the
# steps context and every downstream fork's envp. Only the path may appear.
assert "J4: no body string in GITHUB_OUTPUT (only the path)" \
  bash -c "! grep -qE '^(summary|prefix)(<<|=)' '${GITHUB_OUTPUT}' && ! grep -qF 'Show Test Report' '${GITHUB_OUTPUT}'"
assert "J4: GITHUB_OUTPUT holds exactly one output line" \
  test "$(wc -l < "${GITHUB_OUTPUT}")" -eq 1
teardown

# A test file name with a path separator must not become a nested path.
setup
export input_test_file="nested/dir/main.tftest.hcl"
export input_test_report="${RUNNER_TEMP}/does-not-exist.txt"
run_step
_bf="$(rendered_body_file)"
assert "J4: path separators in the test file name are flattened" \
  test "$(basename "${_bf}")" = "tf-test-report-nested_dir_main.tftest.hcl.md"
assert "J4: ... and the heading still shows the original name" \
  grep -qF 'for file: `nested/dir/main.tftest.hcl`' "${_bf}"
teardown

# --------------------------------------------------------------------------
# J2 — over-budget report: capped, line-aligned, valid UTF-8
# --------------------------------------------------------------------------
# Multi-byte padding (em-dashes, 3 bytes each) makes a byte-offset cut
# overwhelmingly likely to land mid-codepoint if it is not line-anchored.
over_budget_report_is_capped_cleanly() {
  local bf; bf="$(rendered_body_file)"
  local block
  block=$(awk '/^```terraform$/{f=1;next}/^```$/{f=0}f' "${bf}")
  local len; len=$(printf '%s' "${block}" | wc -c)
  [ "${len}" -le 65000 ] || { echo "report block is ${len} bytes, budget is 65000"; return 1; }
  [ "${len}" -ge 60000 ] || { echo "report block unexpectedly small (${len} bytes)"; return 1; }
  printf '%s' "${block}" | iconv -f UTF-8 -t UTF-8 >/dev/null 2>&1 || { echo "report block is not valid UTF-8 — cut landed mid-codepoint"; return 1; }
  # Line-anchored: the first line of the block is a complete padding line,
  # not a fragment. Every padding line starts with the same prefix.
  local first; first=$(printf '%s' "${block}" | head -n1)
  [[ "${first}" == "Test: \"pad_"* ]] || { echo "first block line is a fragment: '${first}'"; return 1; }
  return 0
}
setup
_big="${RUNNER_TEMP}/big-report.txt"
{
  echo "Test result for file: main.tftest.hcl"
  for i in $(seq 1 1500); do
    printf 'Test: "pad_%04d — — — — — — — — — — — — — — — — — — — —" -----> "pass" ✅ \n' "${i}"
  done
  echo '==================== Test summary for file: "Success! 1500 passed, 0 failed." ===================='
} > "${_big}"
export input_test_report="${_big}"
export input_test_summary='"Success! 1500 passed, 0 failed."'
run_step
assert "J2: over-budget report → exit 0" test "${LAST_EXIT}" -eq 0
assert "J2: report block capped ≤65000, line-aligned, valid UTF-8" over_budget_report_is_capped_cleanly
assert "J2: the report's last line survives the cut" \
  grep -qF 'Test summary for file: "Success! 1500 passed, 0 failed."' "$(rendered_body_file)"
teardown

# --------------------------------------------------------------------------
# J6 — 200k report: capped, no ARG_MAX failure anywhere in the step
# --------------------------------------------------------------------------
setup
_huge="${RUNNER_TEMP}/huge-report.txt"
yes 'Test: "x" -----> "pass" ✅ padding padding padding padding padding padding padding' | head -c 200000 > "${_huge}"
export input_test_report="${_huge}"
run_step
assert "J6: 200k report → exit 0 (no E2BIG)" test "${LAST_EXIT}" -eq 0
assert "J6: body-file stays under GitHub's comment limit" \
  test "$(wc -c < "$(rendered_body_file)")" -le 65536
teardown

# --------------------------------------------------------------------------
# J8 — Azure identity values never reach the comment body
# --------------------------------------------------------------------------
# GitHub masks secrets in job logs, not in comments posted through the API.
# terraform errors quote the subscription ID, so the step replaces the values
# of the job's ARM_* identity variables with '***'.
body_has() { grep -qF -- "${1}" "$(rendered_body_file)"; }
body_lacks() { ! grep -qF -- "${1}" "$(rendered_body_file)"; }

setup
export ARM_SUBSCRIPTION_ID="00000000-1111-2222-3333-444444444444"
export ARM_TENANT_ID="55555555-6666-7777-8888-999999999999"
export ARM_CLIENT_SECRET='a*b?[c]&d'
export ARM_CLIENT_ID=""
export input_status_test="failure"
export input_test_summary='"Failure! 0 passed, 1 failed."'
export input_test_report="${DATA_DIR}/report_identity.txt"
run_step
assert "J8: exit 0" test "${LAST_EXIT}" -eq 0
assert "J8: subscription ID is redacted" body_lacks "00000000-1111-2222-3333-444444444444"
assert "J8: ... where terraform quoted it" body_has 'Subscription: "***"'
assert "J8: tenant ID is redacted" body_has 'Tenant: "***"'
assert "J8: a value with glob and & characters is matched literally" body_has 'secret-with-specials: *** and'
assert "J8: ... and a near miss is left alone" body_has 'must stay: aXb?[c]&d'
assert "J8: the rest of the report is intact" body_has 'Resource Group Name: "rg-example-1-qu41"'
assert "J8: the step log is redacted too" bash -c "! grep -qF '00000000-1111-2222-3333-444444444444' '${OUT_FILE}'"
teardown

# An empty identity variable must not redact anything: an empty pattern would
# otherwise match everywhere.
setup
export ARM_SUBSCRIPTION_ID=""
export ARM_CLIENT_ID=""
run_step
assert "J8: empty identity variables leave the golden body unchanged" matches_golden success_with_report
teardown

# --------------------------------------------------------------------------
# Input validation
# --------------------------------------------------------------------------
setup
export input_test_file=""
run_step
assert "validation: empty test-file fails the step" test "${LAST_EXIT}" -ne 0
assert "validation: ... and says why" grep -q "input_test_file is required" "${OUT_FILE}"
teardown

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------
echo ""
echo "========================================"
echo "Tests run:    ${TESTS_RUN}"
echo -e "Tests passed: ${GREEN}${TESTS_PASSED}${NC}"
echo -e "Tests failed: ${RED}${TESTS_FAILED}${NC}"
echo "========================================"

if [[ ${TESTS_FAILED} -gt 0 ]]; then
  exit 1
fi
exit 0
