#!/bin/env bash
#
# Test runner for create-test-report.
#
# Golden-file suite. test-data/golden_<scenario>.md holds the byte-exact body
# the action produced for each scenario BEFORE it was converted from the
# legacy inline-bash layout (docs/Apply-and-destroy-reporting.md P23, J1).
# The goldens were generated by running the legacy `create-test-summary`
# step through extract_step_source.py — the real YAML-processed run block,
# not a transcription of it — so they are ground truth, not a reading of
# the heredoc indentation.
#
# The action under test must reproduce every golden byte for byte.
#

_this_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0
TESTS_RUN=0

DATA_DIR="${_this_script_dir}/test-data"
OUT_FILE=/tmp/test_output_create_test_report.txt

# --------------------------------------------------------------------------
# Harness
# --------------------------------------------------------------------------

setup() {
  export GITHUB_OUTPUT=$(mktemp)
  export RUNNER_TEMP=$(mktemp -d)
  export GITHUB_ACTION_PATH="${_this_script_dir}"
  export GITHUB_WORKSPACE="${RUNNER_TEMP}"
  export GITHUB_WORKFLOW="DSB Terraform Module CI"
  export GITHUB_ACTOR="octo-user"
  export GITHUB_EVENT_NAME="pull_request"

  # Inputs, as the action.yml shim exports them. The legacy step read these
  # under the upper-case names; the converted step reads input_*. Both are
  # exported so the same fixture setup drives either implementation.
  export input_test_file="main.tftest.hcl"
  export input_test_out_file="${RUNNER_TEMP}/results.json"
  export input_status_init="success"
  export input_status_test="success"
  export input_test_summary='"Success! 2 passed, 0 failed."'
  export input_test_report="${DATA_DIR}/report_success.txt"
}

teardown() {
  rm -f "${GITHUB_OUTPUT}"
  rm -rf "${RUNNER_TEMP}"
}

# Run the LEGACY step: extract the `create-test-summary` run block from
# action.yaml with the GitHub expressions substituted, and execute it under
# the runner's shell flags. Replaced by the converted step script in the
# conversion commit; the goldens do not change.
run_step() {
  local step="${RUNNER_TEMP}/legacy-step.sh"
  python3 "${_this_script_dir}/extract_step_source.py" \
    "${_this_script_dir}/action.yaml" create-test-summary "${step}" \
    "inputs.test-file=${input_test_file}" \
    "github.actor=${GITHUB_ACTOR}" \
    "github.event_name=${GITHUB_EVENT_NAME}" \
    "github.action_path=${_this_script_dir}"
  (
    export TEST_OUT_FILE="${input_test_out_file}"
    export STATUS_INIT="${input_status_init}"
    export STATUS_TEST="${input_status_test}"
    export TEST_SUMMARY="${input_test_summary}"
    export TEST_REPORT="${input_test_report}"
    bash --noprofile --norc -eo pipefail "${step}"
  ) >"${OUT_FILE}" 2>&1
  LAST_EXIT=$?
}

# The rendered body, however the implementation under test exposes it.
# Legacy: the multiline `summary` step output.
rendered_body_file() {
  local out="${RUNNER_TEMP}/rendered-body.md"
  python3 - "${GITHUB_OUTPUT}" "${out}" <<'PY'
import sys, re
src, dst = sys.argv[1:3]
txt = open(src, encoding='utf-8').read()
m = re.search(r'^summary<<(".*?")\n(.*?)\n\1\n', txt, re.S | re.M)
open(dst, 'w', encoding='utf-8').write(m.group(2) if m else '')
PY
  echo "${out}"
}

assert() {
  local name="${1}"
  shift
  TESTS_RUN=$((TESTS_RUN + 1))
  echo -e "${BLUE}TEST ${TESTS_RUN}: ${name}${NC}"
  if "$@"; then
    echo -e "${GREEN}✓ PASSED${NC}"
    TESTS_PASSED=$((TESTS_PASSED + 1))
  else
    echo -e "${RED}✗ FAILED${NC}"
    echo "--- step output ---"
    cat "${OUT_FILE}" 2>/dev/null || true
    echo "--- GITHUB_OUTPUT ---"
    cat "${GITHUB_OUTPUT}" 2>/dev/null || true
    echo "--- end ---"
    TESTS_FAILED=$((TESTS_FAILED + 1))
  fi
}

# Byte-exact comparison against a golden, with a diff on failure.
matches_golden() {
  local golden="${DATA_DIR}/golden_${1}.md"
  local actual
  actual="$(rendered_body_file)"
  if cmp -s "${golden}" "${actual}"; then
    return 0
  fi
  echo "  body differs from ${golden##*/}:"
  diff "${golden}" "${actual}" | sed 's/^/    /'
  return 1
}

echo ""
echo -e "${YELLOW}============================================${NC}"
echo -e "${YELLOW}        CREATE-TEST-REPORT GOLDEN TESTS      ${NC}"
echo -e "${YELLOW}============================================${NC}"

# --------------------------------------------------------------------------
# J1 — every pinned scenario reproduces its golden byte for byte
# --------------------------------------------------------------------------

setup
run_step
assert "J1: success with report → golden" test "${LAST_EXIT}" -eq 0
assert "J1: success with report → byte-exact" matches_golden success_with_report
teardown

setup
export input_status_test="failure"
export input_test_summary='"Failure! 1 passed, 1 failed."'
export input_test_report="${DATA_DIR}/report_failure.txt"
run_step
assert "J1: failure with report → byte-exact" matches_golden failure_with_report
teardown

setup
export input_test_report="${RUNNER_TEMP}/does-not-exist.txt"
run_step
assert "J3: report file missing → exit 0" test "${LAST_EXIT}" -eq 0
assert "J3: report file missing → 'Test report not available' golden" matches_golden report_missing
teardown

setup
export input_status_init="failure"
export input_status_test="skipped"
export input_test_summary=""
export input_test_report="${RUNNER_TEMP}/does-not-exist.txt"
run_step
assert "J1: init failed, tests skipped → <kbd> cells golden" matches_golden init_failed
teardown

setup
export input_status_test="failure"
export input_test_summary='"Error: test run aborted"'
export input_test_report="${DATA_DIR}/report_failure.txt"
run_step
assert "J5: summary without 'Success!' → ❌ golden" matches_golden summary_not_success
teardown

setup
export input_test_file="øæå.tftest.hcl"
export input_test_report="${DATA_DIR}/report_nonascii.txt"
run_step
assert "J7: non-ASCII file name and report → byte-exact" matches_golden non_ascii
teardown

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------
echo ""
echo "========================================"
echo "Tests run:    ${TESTS_RUN}"
echo -e "Tests passed: ${GREEN}${TESTS_PASSED}${NC}"
echo -e "Tests failed: ${RED}${TESTS_FAILED}${NC}"
echo "========================================"

if [[ ${TESTS_FAILED} -gt 0 ]]; then
  exit 1
fi
exit 0
