name: DSB Terraform module release
#
# A requirement for this workflow to run is that the following 'permissions' are granted by the calling workflow:
#   permissions:
#     contents: write  # required for release-please to create a release PR
#     pull-requests: write   # required for release-please to create a release PR
on:
  workflow_call:

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: terraform-module
